[theme]
base = "dark"
primaryColor = "#FF3333"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#141414"
textColor = "#EDEDED"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
